# Use this inventory when running the playbook from inside the VM itself.
# ansible-playbook -i inventory_local.ini install.yml

[arr_servers]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
